### PR TITLE
Issue/#49 50

### PR DESCRIPTION
**Pull request by philboeselager**

### CODE REVIEW

**Comment by dr0i** [comment]
The description of the pull request is missing. Also, the refererence in the branch name of the PR and in the comments of the commits to the issue #49 does not exist.

**Comment by philboeselager** [comment]
> The description of the pull request is missing. Also, the refererence in the branch name of the PR and in the comments of the commits to the issue #49 does not exist.

Sorry. I've forgotten to mention https://github.com/hbz/lobid-organisations/issues/49 resp. https://github.com/hbz/lobid-organisations/issues/50 . The purpose of this pull is simply to improve the functionality in order to serve properly for these two issues.

> Seems like 'Ã' should be substituted by more than one character (Ä, Ö, Ü ...) which cannot be intended.( But this could also be a rendering issue in my Browser?)

That looks like a such rendering issue. Works fine.

**Comment by dr0i** [comment]
Ok then. Would be nice, though, to have the proper reference you provided also in the commit messages.
Could you amend the commit messages?

**Comment by philboeselager** [comment]
> Could you amend the commit messages?

Done.

**Pull request merged**
